#!/usr/bin/env node
// keybridge v2 installer.
//   node install.mjs [--ext-id <id>] [--backend software|secure-enclave]
//
// - derives the unpacked extension ID from the extension dir path (or takes
//   --ext-id if you copied it from chrome://extensions)
// - registers the native-messaging host manifest for Chrome
// - builds + ad-hoc-signs the Swift Secure Enclave helper (macOS)
// - probes which signing backend works and records it in ~/.keybridge/config.json
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { writeFileSync, mkdirSync, chmodSync, existsSync, copyFileSync, realpathSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { homedir, platform } from 'node:os'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const KB_DIR = join(homedir(), '.keybridge')
const HOST_NAME = 'bi.atomic.keybridge.webauthn'
const EXT_DIR = join(HERE, 'extension')
const HOST_JS = join(HERE, 'host', 'keybridge-webauthn-host.js')

const args = process.argv.slice(2)
const getArg = (name) => { const i = args.indexOf(name); return i !== -1 ? args[i + 1] : undefined }

// Chrome derives an unpacked extension's ID from the SHA-256 of its absolute
// path: first 16 bytes, each nibble mapped 0..15 -> 'a'..'p'.
function extIdFromPath (absPath) {
  const hash = createHash('sha256').update(absPath, 'utf8').digest()
  let id = ''
  for (let i = 0; i < 16; i++) {
    id += String.fromCharCode(97 + (hash[i] >> 4))
    id += String.fromCharCode(97 + (hash[i] & 0x0f))
  }
  return id
}

const extId = getArg('--ext-id') || extIdFromPath(resolve(EXT_DIR))
console.log(`• extension id: ${extId}${getArg('--ext-id') ? ' (from --ext-id)' : ' (derived from path)'}`)

mkdirSync(KB_DIR, { recursive: true })

// 1. native-messaging host manifest — written to every Chromium-family
// browser dir that exists on this machine.
//
// Chrome launches native-messaging hosts with a stripped-down PATH (roughly
// /usr/bin:/bin:/usr/sbin:/sbin), so a `#!/usr/bin/env node` shebang fails to
// find Node when it lives in fnm/nvm/Homebrew — Chrome then reports "Native
// host has exited". We point the manifest at a tiny /bin/sh launcher that execs
// an ABSOLUTE node path (resolved from the interpreter running this installer).
chmodSync(HOST_JS, 0o755)
const NODE_BIN = realpathSync(process.execPath)
const LAUNCHER = join(KB_DIR, 'keybridge-launch.sh')
writeFileSync(LAUNCHER, `#!/bin/sh\n# Auto-generated by keybridge install.mjs — launches the host with an absolute\n# node path so it works under Chrome's restricted native-messaging PATH.\nexec "${NODE_BIN}" "${HOST_JS}" "$@"\n`)
chmodSync(LAUNCHER, 0o755)
console.log(`• host launcher -> ${LAUNCHER}  (node: ${NODE_BIN})`)
const hostManifest = {
  name: HOST_NAME,
  description: 'keybridge WebAuthn signing host',
  path: LAUNCHER,
  type: 'stdio',
  allowed_origins: [`chrome-extension://${extId}/`],
}
const nmDirs = platform() === 'darwin'
  ? [
      'Google/Chrome', 'Google/Chrome Beta', 'Google/Chrome Canary', 'Chromium',
      'BraveSoftware/Brave-Browser', 'Microsoft Edge',
    ].map((b) => join(homedir(), 'Library', 'Application Support', b, 'NativeMessagingHosts'))
  : [
      join(homedir(), '.config', 'google-chrome', 'NativeMessagingHosts'),
      join(homedir(), '.config', 'chromium', 'NativeMessagingHosts'),
    ]

let wrote = 0
for (const dir of nmDirs) {
  const parent = dirname(dir)
  if (!existsSync(parent)) continue // that browser isn't installed
  mkdirSync(dir, { recursive: true })
  writeFileSync(join(dir, `${HOST_NAME}.json`), JSON.stringify(hostManifest, null, 2))
  console.log(`• native host manifest -> ${join(dir, `${HOST_NAME}.json`)}`)
  wrote++
}
if (wrote === 0) console.log('! no Chromium-family browser dirs found; is Chrome installed for this user?')

// Also register the host inside the isolated test profile driven by the
// chrome-devtools MCP. On macOS, Chrome launched with a custom --user-data-dir
// resolves user-level native-messaging hosts under <user-data-dir>/
// NativeMessagingHosts — the standard ~/Library/... path is NOT consulted — so
// the isolated profile needs its own copy of the manifest.
const testProfileNmDir = join(dirname(HERE), '.chrome-dev-profile', 'NativeMessagingHosts')
mkdirSync(testProfileNmDir, { recursive: true })
writeFileSync(join(testProfileNmDir, `${HOST_NAME}.json`), JSON.stringify(hostManifest, null, 2))
console.log(`• native host manifest -> ${join(testProfileNmDir, `${HOST_NAME}.json`)} (chrome-devtools MCP profile)`)

// 2. Swift Secure Enclave helper (macOS only)
let backend = getArg('--backend')
const helperBin = join(KB_DIR, 'keybridge-se-signer')
if (!backend && platform() === 'darwin') {
  try {
    const swiftSrc = join(HERE, 'helper', 'SecureEnclaveSigner.swift')
    console.log('• building Secure Enclave helper (swiftc) ...')
    execFileSync('swiftc', ['-O', swiftSrc, '-o', helperBin], { stdio: 'inherit' })
    // Ad-hoc sign for good measure. The CryptoKit SecureEnclave API stores an
    // on-disk key blob rather than a keychain item, so NO entitlement or
    // provisioning profile is required — an unsigned/ad-hoc binary works.
    try { execFileSync('codesign', ['--force', '--sign', '-', helperBin], { stdio: 'inherit' }) } catch {}
    console.log('• probing Secure Enclave (creates a throwaway key) ...')
    execFileSync(helperBin, ['probe'], { stdio: ['ignore', 'pipe', 'pipe'] })
    backend = 'secure-enclave'
    console.log('  ✓ Secure Enclave available — signatures will require Touch ID')
  } catch (e) {
    backend = 'software'
    console.log(`  ! Secure Enclave not usable (${String(e.message).split('\n')[0]}); falling back to software backend`)
  }
} else if (!backend) {
  backend = 'software'
}

writeFileSync(join(KB_DIR, 'config.json'), JSON.stringify({ backend }, null, 2))
console.log(`• backend: ${backend}  (override anytime with KEYBRIDGE_BACKEND=software|secure-enclave)`)

console.log(`
Next steps:
  1. Open chrome://extensions, enable Developer mode, "Load unpacked" ->
       ${EXT_DIR}
  2. Confirm the ID shown matches:
       ${extId}
     If not, re-run:  node ${join(HERE, 'install.mjs')} --ext-id <the-id-chrome-shows>
  3. Restart Chrome (native-messaging manifests are read at startup).
  4. Visit https://webauthn.io, register + authenticate a passkey.
     ${backend === 'secure-enclave' ? 'You should get a Touch ID prompt on each ceremony.' : 'Signing happens silently in the software backend.'}
`)
